cribbl/miteb-frontend

.env.example, src/Services/NotificationService.js, src/Services/firebaseAuthService.js, src/Services/firebaseStorageService.js
Add `REACT_APP_BACKEND_API` env var and use that as baseURL in services.
Fixes #43 
=> fix: use baseURL based on environment

src/Services/NotificationService.js, src/Services/firebaseDBService.js, src/components/ClassroomComponent/BookingComponent/BookingComponent.js, src/components/ClassroomComponent/MyEventsComponent/MyEventsComponent.js, src/components/ClassroomComponent/MyEventsComponent/SCEventsComponent.js, src/components/Dialogs/ViewEventDialogComponent.js, src/components/DrawerComponent/DrawerComponent.js, src/index.js
Allow SC to approve/reject/flag an event before FA, AD, SO
Closes #50 
=> Feat: Actions on events by SC

src/components/ClassroomComponent/MyEventsComponent/MyEventsComponent.js, src/components/Dialogs/PostEventDetailDialogComponent.js, src/components/Dialogs/ViewEventDialogComponent.js
Add dialog to take post event detail description.
Partially fixes #53 
=> Feat: Post Event detail only description

src/components/ClassroomComponent/ProfileComponent/ProfileContainer.js
Name abbreviation made non editable
Fixes # 36
=> Club name abbreviation made non editable

src/components/ClassroomComponent/BookingComponent/Rooms.js
Block rooms in NLH first floor and 1 room(207) in AB5
=> fix: block some rooms for SC.

src/components/ClassroomComponent/BookingComponent/Rooms.js
Summary of changes:
NLH:
`101,201,301,401` : These rooms are not available for booking and are
hence permanently deleted.
`202,203,204,205,304,305` : These rooms are reserved by SC
`302`: Reserved by Parikshit.
AB5
`207`: Reserved by SC.
=> fix: change blocked rooms as per SC direction.

src/components/Dialogs/ViewEventDialogComponent.js
AB5 310A and 310B weren't handled properly in the code which led to a bug.
Handle those 2 rooms separately.
Trivial fix.
=> fix: Fixes bug caused by 2 rooms in AB5

src/Services/firebaseDBService.js, src/components/ClassroomComponent/ViewBookings/EventDetailsComponent.js, src/components/ClassroomComponent/ViewBookings/Rooms.js, src/components/ClassroomComponent/ViewBookings/ViewBookingsComponent.js, src/components/DrawerComponent/DrawerComponent.js, src/index.js
Student Council requires to keep track of which rooms are occupied by
which club so that they can control the room bookings. This feature
helps achieve the Council to get information regarding which event is
going to be held at a particular room at a particular day.
=> feat: Add admin page for Student Council.

src/Services/firebaseDBService.js, src/components/ClassroomComponent/BookingComponent/BookingComponent.js
This fixes the mysterious anonymous rooms in roomsx error.
For eg. Consider there is a booking for the 29th. Now when someone
books rooms from 28-30 the rooms for 29th will incorrectly be added to
the roomsx array for 28 and 30 also. This was caused because taken rooms
was calculated across all booking dates and then when roomsx was to be
updated the same array of takenRooms concatenated with selectedRooms was
used to update all dates.
=> fix: Critical bug fix involving the room booking logic

src/components/LandingPage/Footer.js, src/components/Policies/PrivacyPolicy.js
Update phone number from @bhawesh96 's to mine.
=> fix: Update phone numbers

src/components/ClassroomComponent/BookingComponent/Rooms.js
Temporarily disable NLH rooms 202 and 205.
=> [3202,3205] Disable NLH rooms

src/Services/firebaseDBService.js, src/components/ClassroomComponent/ViewBookingsComponent/EventDetailsComponent.js, src/components/ClassroomComponent/ViewBookingsComponent/Rooms.js, src/components/ClassroomComponent/ViewBookingsComponent/ViewBookingsComponent.js
The floor incharges need a list of approved rooms to verify the receipts presented by the clubs. To achieve that I have color coded the Approved rooms in the View Bookings tab.
Open to a better solution for the long run.
=> Show approved rooms on View Bookings tab.

src/Services/firebaseDBService.js, src/components/ClassroomComponent/ViewBookingsComponent/ViewBookingsComponent.js
Earlier all approved rooms were fetched. In this commit only approved
rooms for the selected date are fetched.
=> fix: Fix logical error in color coding approved rooms

src/Services/firebaseDBService.js
Arguments passed were of the form `DD-MM-YYYY` so was not being properly parsed by moment.
=> fix: Pass properly formatted date arguments to getDateArr in addApprovedRooms

src/Services/firebaseDBService.js, src/components/ClassroomComponent/ViewBookingsComponent/Rooms.js, src/components/ClassroomComponent/ViewBookingsComponent/ViewBookingsComponent.js
Display blocked rooms as disabled with a red background.
=> feat: Handle blocked rooms in View Bookings

src/components/ClassroomComponent/MyEventsComponent/MyEventsComponent.js, src/components/Dialogs/CancelEventDialogComponent.js
This deletes the entire event description from the database.
Fixes #65
=> Feature: Allow clubs to cancel event bookings

src/Services/firebaseDBService.js, src/Services/firebaseStorageService.js
Email template was being sent without the receipt URL causing the
receipt link to malfunction in the email.
Send email template ***after*** the PDF has been generated and the link
has been generated.
=> fix: Buggy Receipt in Event Approved email.

src/components/ComplaintsComponent/ComplaintsContent.js
Add an option 'Portal' in the dropdown of subjects under complaints.
Closes #86 
Note: this merge is more to test the auto-deployment to prod
=> Feat: Add 'Portal' in complaint subject

src/components/ClassroomComponent/ViewBookingsComponent/ViewBookingsComponent.js
This is a critical feature needed by the SO wherein he needs a list of approved rooms for the day
=> feat: add support to export approved rooms for the day

src/Services/firebaseDBService.js
=> Add events to "to-be-held" only when it is approved by all authorities

src/components/ClassroomComponent/ApproveClubsComponent/ApproveClubsContainer.js
Include a summary of the change and relevant motivation/context. List any dependencies that are required for this change.
Fixes #101
=> fix: filter undefined values from arr in approve clubs

src/Services/firebaseDBService.js
When any authority rejects the rooms gets unblocked.
Fixes # 66
=> feat: unblock rooms when an authority rejects

src/components/ClassroomComponent/BookingComponent/BookingComponent.js, src/components/ClassroomComponent/BookingComponent/Rooms.js
Security Officer needs to be able to book rooms for a variety of reasons but this feature was broken for the SO for some reasons. (SO has no FA etc. )
This PR fixes this functionality for SO and also changes the Room Booking process a bit.
For instance the SO need not enter booker info like name, email, registration number etc.
TODO: This PR introduces some ugly code into `BookingComponent.js` which should be refactored later.
Fixes #98 
We dont have tests yet so manually tested :(
This stuff in the issue template feels unnecessary what say @bhawesh96
=> Allow SO to book rooms

src/components/ClassroomComponent/BookingComponent/BookingComponent.js
Closes #107
Some registration numbers were not being accepted, for example, 190911112 is not getting accepted while creating an event.
Fixes #107
=> Fix registration number bug
